#ifndef MACH_S3_UI_STRINGS_H
#define MACH_S3_UI_STRINGS_H

/* GENERATED from ui_strings.json by scripts/gen-ui-strings.js - do not edit. */

#define UI_STR_PAUSE_MENU "设置"
#define UI_STR_FLOPPY_MANAGER "软盘管理"
#define UI_STR_QUICK_SETTINGS "快捷设置"
#define UI_STR_BACKLIGHT "背光"
#define UI_STR_VOLUME "音量"
#define UI_STR_INSERT "插入"
#define UI_STR_RESUME "继续"
#define UI_STR_REBOOT "重启"
#define UI_STR_RECOVER_UPDATE "恢复/更新"
#define UI_STR_SELECT_FLOPPY_FIRST "请先选择软盘"
#define UI_STR_INSERT_UNAVAILABLE "无法插入，请重试"
#define UI_STR_INSERT_FAILED "插入失败，请重试"
#define UI_STR_INSERTED "已插入"
#define UI_STR_REBOOT_UNAVAILABLE "无法重启"
#define UI_STR_REBOOTING "正在重启…"
#define UI_STR_CANNOT_INSERT_INVALID "无法插入：无效选择"
#define UI_STR_DISK_OCCUPIED "无法插入：磁盘已占用，请在 Mac 系统中弹出"
#define UI_STR_CANNOT_EJECT_HERE "无法在此弹出，请在 Mac 系统中操作"
#define UI_STR_NETWORK "网络"
#define UI_STR_HOTSPOT_KEYS "热点：\n密码：\nIP："
#define UI_STR_WIFI_KEYS "WiFi：\n密码：\nIP：\nmDNS："
#define UI_STR_WIFI_KEYS_SHORT "WiFi：\n密码："
#define UI_STR_PROVISION "配网"
#define UI_STR_REPROVISION "重新配网"
#define UI_STR_STATE_OFF "已关闭"
#define UI_STR_STATE_PROVISIONING "配网中"
#define UI_STR_STATE_CONNECTING "连接中…"
#define UI_STR_STATE_CONNECTED "已连接"
#define UI_STR_STATE_RECONNECTING "重连中…"
#define UI_STR_STATE_AP_ONLY "热点"
#define UI_STR_HINT_HOLD_PROVISION "长按后部按钮配网"
#define UI_STR_HINT_CONNECT_HOTSPOT "手机连接此热点配网"
#define UI_STR_HINT_HOLD_BUTTON "长按后部按钮配网"
#define UI_STR_FLASH_STEP1 "1. 用 USB 线连接电脑"
#define UI_STR_FLASH_STEP2 "2. 打开网页刷机工具选择固件"
#define UI_STR_FLASH_STEP3 "3. 此模式下 USB 键盘已禁用"
#define UI_STR_FLASH_EXIT "退出：断电重启设备"
#define UI_STR_SYSTEM_UPGRADE "系统升级"
#define UI_STR_PREPARING "准备中…"
#define UI_STR_UPGRADE_ERR_READ_HEADER "读取文件头失败"
#define UI_STR_UPGRADE_ERR_INVALID_FILE "升级文件无效"
#define UI_STR_UPGRADE_ERR_UNSUPPORTED_VER "不支持的升级版本"
#define UI_STR_UPGRADE_ERR_EMPTY_FILE "升级文件为空"
#define UI_STR_UPGRADE_ERR_OOM "内存不足"
#define UI_STR_UPGRADE_ERR_READ_ENTRIES "读取条目表失败"
#define UI_STR_UPGRADE_ERR_SD_SEEK "SD 卡寻址错误"
#define UI_STR_UPGRADE_ERR_NO_OTA_SLOT "无可用 OTA 分区"
#define UI_STR_UPGRADE_ERR_TOO_LARGE "固件超出分区大小"
#define UI_STR_UPGRADE_ERR_SD_READ "SD 卡读取错误"
#define UI_STR_UPGRADE_ERR_HD_NOT_FOUND "未找到硬盘分区"
#define UI_STR_UPGRADE_ERR_HD_TOO_LARGE "硬盘镜像过大"
#define UI_STR_UPGRADE_ERR_HD_ERASE "硬盘擦除失败"
#define UI_STR_UPGRADE_ERR_HD_WRITE "硬盘写入失败"
#define UI_STR_UPGRADE_STAGE_WRITE_FW "正在写入固件…"
#define UI_STR_UPGRADE_STAGE_ERASE_HD "正在擦除硬盘…"
#define UI_STR_UPGRADE_STAGE_WRITE_HD "正在写入硬盘镜像…"

#endif /* MACH_S3_UI_STRINGS_H */
